name: redix_test
services:
  db:
    image: docker.io/postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: no
  redis:
    image: redis:6-alpine
    restart: no
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass miTAhlInEWlI
